version: 2
jobs:
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3 bucket
          command: aws s3 sync . s3://adi-static-aws-circleci/ --exclude '.circleci/*' --exclude '.git/*'  
  - request-testing:
          type: approval
          requires:
            - deploy
      - deploy-aws:
          requires:
            - request-testing  


workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy
      - deploy-prod
         --- approval
         requires deply