version: 2
jobs:
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run:
          name: Install awscli
          command: sudo pip install awscli
  deploy-aws:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - run:
          name: Deploy to S3 bucket
          command: aws s3 sync . s3://adi-static-aws-circleci/ --exclude '.circleci/*' --exclude '.git/*'


workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy
      - deploy-aws:
          type: approval
          requires:
            - deploy